### ISSUE TITLE
[Feat] 배송 담당자 API

### ISSUE THREAD

**Issue by M1ngD0ng** [Logistics-system-project/Delivery-service#1]
## Description
> 설명

배송 담당자 관리 기능

## Requirements
> 기능 구현을 위한 요구사항
- 배송 담당자의 ID는 User 엔티티의 ID와 동일해야 함
- 업체 배송 담당자 생성/수정 시, 소속 허브 ID가 존재하는 허브인지 확인 필요
- 배송 담당자는 순차적으로 배정
- is_deleted 필드를 사용하여 논리적 삭제 관리

## Estimated Duration
12/11(수) ~ 12/12 (목) [2일]

## Todo
> 기능 구현을 위한 할 일 작성
- [x] 배송 담당자 entity 생성
- [x] 배송 담당자 목록 조회 기능 구현
- [x] 배송 담당자 상세 조회 기능 구현
- [x] 배송 담당자 수정 기능 구현
- [x] 배송 담당자 삭제 기능 구현
